version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: taskmanager-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: taskmanager
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: taskmanagerservice
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
